# Generated by Django 3.0.2 on 2020-06-14 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_type', models.CharField(choices=[('Sedan', 'Sedan'), ('Coupe', 'Coupe'), ('Hatchback', 'Hatchback'), ('SUV', 'SUV'), ('Pick Up', 'Pick Up'), ('Van', 'Van'), ('Mini Van', 'Mini Van'), ('Wagon', 'Wagon'), ('Convertible', 'Convertible'), ('Bus', 'Bus'), ('Truck', 'Truck'), ('Heavy Equipment', 'Heavy Equipment'), ('Agricultural Equipment', 'Agricultural Equipment')], max_length=100)),
                ('sub_body_type', models.CharField(choices=[('Flat Body', 'Flat Body'), ('Crane', 'Crane'), ('Dump', 'Dump'), ('Loader', 'Loader'), ('Chassis', 'Chassis'), ('Garbage Truck', 'Garbage Truck'), ('High Elevation Work Truck', 'High Elevation Work Truck'), ('Self', 'Self'), ('Fork Lift', 'Fork Lift'), ('Mini Excavator', 'Mini Excavator'), ('Dozer', 'Dozer'), ('Excavator', 'Excavator'), ('Rollers', 'Graders'), ('Finishers', 'Finishers'), ('Attachments', 'Attachments'), ('Box', 'Box'), ('Compressor', 'Compressor'), ('Double Cabin', 'Double Cabin'), ('Tractor', 'Tractor')], max_length=100)),
                ('steering', models.CharField(choices=[('Right Hand Drive', 'Right Hand Drive'), ('Left Hand Drive', 'Left Hand Drive')], max_length=80)),
                ('transmission', models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual'), ('Smoother', 'Smoother'), ('Semi AT', 'Semi AT'), ('Inomat', 'Inomat'), ('Duonic', 'Duonic'), ('Escot', 'Escot'), ('Proshift', 'Proshift')], max_length=80)),
                ('fuel', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('LPG', 'LPG'), ('Electric Vehicle', 'Electric Vehicle'), ('Hybrid(Petrol)', 'Hybrid(Petrol)'), ('Hybrid(Diesel)', 'Hybrid(Diesel)')], max_length=80)),
                ('color', models.CharField(choices=[('Beige', 'Beige'), ('Black', 'Black'), ('Blue', 'Blue'), ('Cream', 'Cream'), ('Gold', 'Gold'), ('Gray', 'Gray'), ('Green', 'Green'), ('Orange', 'Orange'), ('Pearl', 'Pearl'), ('Pink', 'Pink'), ('Purple', 'Purple'), ('Red', 'Red'), ('Rose', 'Rose'), ('Silver', 'Silver'), ('White', 'White')], max_length=30)),
                ('loading_capacity', models.CharField(choices=[('Under 1 ton', 'Under 1 ton'), ('1 to 2 ton', '1 to 2 ton'), ('2 to 2.5 ton', '2 to 2.5 ton'), ('2.5 to 3 ton', '2.5 to 3 ton'), ('3 to 4 ton', '3 to 4 ton'), ('4 to 5 ton', '4 to 5 ton'), ('4 to 5 ton', '4 to 5 ton'), ('5 to 6 ton', '5 to 6 ton'), ('6 to 7 ton', '6 to 7 ton'), ('7 to 8 ton', '7 to 8 ton'), ('8 to 9 ton', '8 to 9 ton'), ('9 to 10 ton', '9 to 10 ton'), ('Over 10 ton', 'Over 10 ton')], max_length=100)),
                ('body_length', models.CharField(choices=[('Under 3400mm', 'Under 3400mm'), ('3400 to 4000mm', '3400 to 4000mm'), ('4000 to 4500mm', '4000 to 4500mm'), ('4500 to 4700mm', '4500 to 4700mm'), ('4700 to 4795mm', '4700 to 4795mm'), ('4795 to 5000mm', '4795 to 5000mm'), ('5000 to 5100mm', '5000 to 5100mm'), ('Over 5100mm', 'Over 5100mm')], max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.IntegerField(default=5000)),
                ('airbag', models.BooleanField(default=True)),
                ('grill_guard', models.BooleanField(default=False)),
                ('rear_spoiler', models.BooleanField(default=False)),
                ('anti_lock_brake_system', models.BooleanField(default=True)),
                ('leather_seats', models.BooleanField(default=True)),
                ('sun_roof', models.BooleanField(default=False)),
                ('air_conditioner', models.BooleanField(default=True)),
                ('navigation', models.BooleanField(default=True)),
                ('tv', models.BooleanField(default=False)),
                ('alloy_wheels', models.BooleanField(default=False)),
                ('power_steering', models.BooleanField(default=True)),
                ('dual_air_bags', models.BooleanField(default=True)),
                ('back_tire', models.BooleanField(default=True)),
                ('power_windows', models.BooleanField(default=False)),
                ('fog_lights', models.BooleanField(default=True)),
                ('roof_rails', models.BooleanField(default=False)),
                ('image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Cars',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateTimeField()),
                ('read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('id_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=500)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('street', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=100)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Manufacturers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Manufacturers',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField(auto_now=True)),
                ('date_due', models.DateTimeField()),
                ('completed', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motorhub.Cars')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motorhub.Customers')),
            ],
            options={
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(max_length=100000)),
                ('read', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motorhub.Customers')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motorhub.Cars')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motorhub.Customers')),
            ],
        ),
        migrations.AddField(
            model_name='cars',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motorhub.Manufacturers'),
        ),
    ]
