# Generated by Django 3.0.5 on 2020-05-29 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motorhub', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='make',
            new_name='manufacturer',
        ),
    ]
