# Generated by Django 3.0.2 on 2020-07-07 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorhub', '0002_delete_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='email_verfied',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cars',
            name='color',
            field=models.CharField(choices=[('Beige', 'Beige'), ('Black', 'Black'), ('Blue', 'Blue'), ('Cream', 'Cream'), ('Gold', 'Gold'), ('Gray', 'Gray'), ('Green', 'Green'), ('Orange', 'Orange'), ('Pearl', 'Pearl'), ('Pink', 'Pink'), ('Purple', 'Purple'), ('Red', 'Red'), ('Rose', 'Rose'), ('Silver', 'Silver'), ('White', 'White'), ('White', 'White'), ('Yellow', 'Yellow'), ('Brown', 'Brown')], max_length=30),
        ),
    ]
