# Generated by Django 3.0.2 on 2020-07-12 00:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorhub', '0003_auto_20200707_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='date_due',
            field=models.DateField(default=datetime.datetime(2020, 7, 19, 3, 27, 55, 859873)),
        ),
    ]
