# Generated by Django 3.0.5 on 2020-05-30 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motorhub', '0004_contact_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
    ]
