# Generated by Django 3.0.5 on 2020-05-30 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorhub', '0005_remove_contact_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
