# Generated by Django 3.0.2 on 2020-07-12 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorhub', '0005_auto_20200712_0355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notifications',
            options={'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterField(
            model_name='orders',
            name='date_due',
            field=models.DateField(default=datetime.datetime(2020, 7, 19, 15, 39, 42, 738112)),
        ),
    ]
