# Generated by Django 3.0.5 on 2020-06-02 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motorhub', '0006_contact_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='confirm_password',
        ),
    ]
