# Generated by Django 3.1.6 on 2021-02-11 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorhub', '0006_auto_20200712_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='date_due',
            field=models.DateField(default=datetime.datetime(2021, 2, 18, 12, 40, 3, 884289)),
        ),
    ]
